server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8088

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables dynamic route discovery from Eureka
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customerService/**
        
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/petService/**
        
        - id: vet-service
          uri: lb://vet-service
          predicates:
            - Path=/vetService/**

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
